### ISSUE TITLE
Configure Social/Facebook app for integration tests

### ISSUE THREAD

**Issue by FlowFX** [FlowFX/reggae-cdmx.com#182]
```
232 WARNING  Exception raised while rendering {% include %} for template 'account/login.html'. Empty string rendered instead.
Traceback (most recent call last):
  File "/Users/flowfx/.virtualenvs/reggae-cdmx/lib/python3.6/site-packages/allauth/socialaccount/providers/facebook/provider.py", line 141, in media_js
    app = self.get_app(request)
  File "/Users/flowfx/.virtualenvs/reggae-cdmx/lib/python3.6/site-packages/allauth/socialaccount/providers/base.py", line 52, in get_app
    return SocialApp.objects.get_current(self.id, request)
  File "/Users/flowfx/.virtualenvs/reggae-cdmx/lib/python3.6/site-packages/allauth/socialaccount/models.py", line 40, in get_current
    provider=provider)
  File "/Users/flowfx/.virtualenvs/reggae-cdmx/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/flowfx/.virtualenvs/reggae-cdmx/lib/python3.6/site-packages/django/db/models/query.py", line 380, in get
    self.model._meta.object_name
allauth.socialaccount.models.DoesNotExist: SocialApp matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/flowfx/.virtualenvs/reggae-cdmx/lib/python3.6/site-packages/django/template/loader_tags.py", line 216, in render
    return template.render(context)
  File "/Users/flowfx/.virtualenvs/reggae-cdmx/lib/python3.6/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/Users/flowfx/.virtualenvs/reggae-cdmx/lib/python3.6/site-packages/django/test/utils.py", line 107, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Users/flowfx/.virtualenvs/reggae-cdmx/lib/python3.6/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/Users/flowfx/.virtualenvs/reggae-cdmx/lib/python3.6/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Users/flowfx/.virtualenvs/reggae-cdmx/lib/python3.6/site-packages/allauth/socialaccount/templatetags/socialaccount.py", line 65, in render
    for p in providers.registry.get_list(request)])
  File "/Users/flowfx/.virtualenvs/reggae-cdmx/lib/python3.6/site-packages/allauth/socialaccount/templatetags/socialaccount.py", line 65, in <listcomp>
    for p in providers.registry.get_list(request)])
  File "/Users/flowfx/.virtualenvs/reggae-cdmx/lib/python3.6/site-packages/allauth/socialaccount/providers/facebook/provider.py", line 143, in media_js
    raise ImproperlyConfigured("No Facebook app configured: please"
django.core.exceptions.ImproperlyConfigured: No Facebook app configured: please add a SocialApp using the Django admin
```

**Comment by FlowFX** [comment]
Well. It's not an issue at the moment.
